### ISSUE TITLE
Fullstack Login

### ISSUE THREAD

**Issue by mileswatson** [rational-trading/rational-trading#43]
Backend should implement an `/api/login` POST endpoint, that should authenticate the username + password and return some kind of token (either JWT or session). This token should be stored somewhere in the frontend, so that it can be used for future authenticated requests. Modify the `endpoints/auth.py` to validate the new token format. If token refresh is needed should think about some mechanism for this.

**Comment by mileswatson** [comment]
Updated description.

**Comment by dylan-mankin** [comment]
- [ ] JWT create token
- [ ] JWT validate token
- [ ] JWT refresh token
- [ ] DB stuff
- [ ] Frontend

**Comment by mileswatson** [comment]
@dylan-mankin @StefanPitur How's this going?
