### ISSUE TITLE
Investigate NLP / ML

### ISSUE THREAD

**Issue by mileswatson** [rational-trading/rational-trading#9]
Take a look at some Python NLP / ML libraries for tasks that we might need in our project (e.g. extraction, semantic analysis, summarisation), and report findings here.

**Comment by luo-simon** [comment]
Will want to perform NLP/ML to e.g.
- Summaries/classify the sentiment of _Ticker News_ responses provided by Polygon.io API

Possible Python NLP libraries
- NLTK
- spaCy
- CoreNLP
- Gensim
- TextBlob
- Pattern
- PyNLPI

**Comment by luo-simon** [comment]
TextBlob seems like a simple NLP library that can be geared towards sentiment analysis

**Using Text Blob**
It takes text as an input and can return polarity and subjectivity as outputs.

Polarity determines the sentiment of the text. Its values lie in [-1,1] where -1 denotes a highly negative sentiment and 1 denotes a highly positive sentiment.

Subjectivity determines whether a text input is factual information or a personal opinion. Its value lies between [0,1] where a value closer to 0 denotes a piece of factual information and a value closer to 1 denotes a personal opinion.

Question:  _Does positive/negative sentiment correlate to evidence for/against a trade?_

**Comment by luo-simon** [comment]
An alternative is NLTK, which allows more flexibility. We can start from the ground up using NLTK's analysis tools, or use their pre-trained classifier, which has been described as follows. Training our own classifier won't be difficult, maybe just tedious - very similar to the stuff we did in Part IA MLRD, but with more helper functions provided by NLTK for lexing/maths-ing.

> VADER (Valence Aware Dictionary and sEntiment Reasoner).
> Since VADER is pretrained, you can get results more quickly than with many other analyzers. However, VADER is best suited for language used in social media, like short sentences with some slang and abbreviations. It’s less accurate when rating longer, structured sentences, but it’s often a good launching point.

**Comment by luo-simon** [comment]
[Article](https://medium.datadriveninvestor.com/sentiment-analysis-of-stocks-from-financial-news-using-python-82ebdcefb638) that implements something very similar to what we want, based on financial news headlines from [FINVIZ](https://finviz.com/). We could also potentially use this site as another source of evidence.

**Comment by luo-simon** [comment]
Choice between analysing just the headlines VS first paragraph (or whole article). 

Headlines
+ Easiest and most straightforward way; no clean-up needed
+ Lots(!) of headlines available at FINVIZ
- Headlines may not reflect sentiment in article
- Scrape FINVIZ (not difficult, website is easy to scrape)

First paragraph (from Polygon.io Ticker News)
+ Sentiment more accurately reflects sentiment of author
- Need to sanitise text (remove HTML tags; although wouldn't be too difficult)
- Polygon.io provides fewer articles

Whole article
+ Most amount of info available 
- Lots of (difficult?!) scraping and sanitising

Once we have the text we want to classify (from one of the 3 choices above), my (current) personal opinion is we perform text analysis via NLTK's VADER model.
